name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      - name: Update Spring Boot Gradle plugin version
        run: sed -i 's/spring-boot-gradle-plugin:.*/spring-boot-gradle-plugin:<spring-boot-version>/' build.gradle
      
      - name: Build with Gradle
        run: ./gradlew build --no-daemon --console plain
